# Generated by Django 3.2.5 on 2023-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(help_text='Measurement Date'),
        ),
    ]
